[workspace]
authors = ["Jared Lumpe <jared@jaredlumpe.com>"]
channels = ["conda-forge"]
name = "snakekit"
platforms = ["linux-64"]
version = "0.1.0"


# ----------------------------------------- Dependencies ----------------------------------------- #

[dependencies]

[pypi-dependencies]
snakekit = { path = ".", editable = true }


[environments]
default = { features = ["dev", "test"] }


[feature.dev.dependencies]
ipython = "*"


[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"


# --------------------------------------------- Tasks -------------------------------------------- #

[tasks]
